In [40]:
from IPython.display import Image
import pydot
from sklearn.tree import export_graphviz

import pandas as pd
import numpy as np

from sklearn.datasets import load_wine

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sklearn.model_selection import KFold
from sklearn.model_selection import ParameterGrid

from sklearn.metrics import accuracy_score,\
                            confusion_matrix, \
                            precision_score, \
                            recall_score, \
                            f1_score, \
                            classification_report

In [4]:
raw_dataset = load_wine()
X = raw_dataset["data"]
y = raw_dataset["target"]
feature_names = raw_dataset["feature_names"]

In [5]:
dataset = pd.DataFrame(data=X, columns=feature_names)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [7]:
dataset.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [8]:
dataset.nunique()

alcohol                         126
malic_acid                      133
ash                              79
alcalinity_of_ash                63
magnesium                        53
total_phenols                    97
flavanoids                      132
nonflavanoid_phenols             39
proanthocyanins                 101
color_intensity                 132
hue                              78
od280/od315_of_diluted_wines    122
proline                         121
dtype: int64

In [9]:
clf = DecisionTreeClassifier()

clf.fit(X, y)

DecisionTreeClassifier()

In [13]:
tree.export_graphviz(clf, out_file="tree.dot", filled=True)

In [21]:
accuracy_score(y, clf.predict(X))

1.0

In [28]:
x_train, x_test, y_train, y_test = train_test_split(dataset, y, test_size=.2, stratify=y)

'''
We can use stratification: with it, we can preserve the original label distribution.
The stratify parameter requires the array that defines, for each individual,
the subpopulation to which it belongs (in our case, our label).'''


'\nWe can use stratification: with it, we can preserve the original label distribution.\nThe stratify parameter requires the array that defines, for each individual,\nthe subpopulation to which it belongs (in our case, our label).'

In [29]:
clf_v1 = DecisionTreeClassifier()
clf_v1.fit(x_train, y_train)
print(accuracy_score(y_test, clf_v1.predict(x_test)))

0.9444444444444444


In [32]:

'''
the accuracy tells us about the "overall" classifier performance.
If we want to know more detailed information (e.g. which classes we are getting right most of the time,
or what kind of errors we are typically doing), we can resort to other metrics.
'''

y_pred = clf.predict(x_test)
print('Confusion matrix: \n',confusion_matrix(y_test, y_pred))
print('Precision score: ',precision_score(y_test, y_pred, average=None))
print('Recall score: ',recall_score(y_test, y_pred, average=None))
print('F1 score: ',f1_score(y_test, y_pred, average=None))

Confusion matrix: 
 [[12  0  0]
 [ 0 14  0]
 [ 0  0 10]]
Precision score:  [1. 1. 1.]
Recall score:  [1. 1. 1.]
F1 score:  [1. 1. 1.]


In [34]:
'''
We can also use classification_report() to get all of the previous information into a single report
(useful for an overview of the classifier performance).
'''

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        10

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [37]:
params = {
    "max_depth": [None, 2, 3, 4, 5],
    "min_impurity_decrease": [0, .01, .03, .07, .09, .11]
}

accuracies = []
for config in ParameterGrid(params):
    clf = DecisionTreeClassifier(**config)
    clf.fit(x_train, y_train)
    accuracies.append(accuracy_score(y_test, clf.predict(x_test)))
max(accuracies)

0.9444444444444444

In [42]:
'''
In the previous exercise, you searched for the best configuration among a list of possible alternatives.
Since we used our test data to select the model, you may be overfitting on the test data (you may
have selected the configuration that works best for the test set, but which may not be as good on
new data). Typically, you do not want to use the test set for tuning the model’s hyperparameters,
since the test set should only be used as a final evaluation.
For this reason, datasets are typically splitted into
• Training set: used to create the model.
• Validation set: used to assess how good each configuration of a classifier is.
• Test set: used at the end of the hyperparameter tuning, to assess how good our final model is.
However, it often happens that only a limited amount of data is available. In these cases, it is wasteful
to only use a small fraction of the dataset for the actual training. In these cases, cross-validation can
be used to “get rid” of the validation set. You can read more about cross-validation on the course
slides. One popular method of is the k-fold cross-validation. In this, the training set is split into k
partitions. k 􀀀 1 are used for the training, the other one is used validation. This is repeated until all
partitions have been used once for validation.
Sklearn offers the KFold class for doing k-fold cross-validation. You can use this class as follows:
'''

X_train_valid, X_test, y_train_valid, y_test = train_test_split(X, y, stratify=y)
kf = KFold(5)

accuracies = []

for config in ParameterGrid(params):
    clf_accuracies = []
    counts = []

    for train_indices, valid_indices in kf.split(X_train_valid):

        X_train = X_train_valid[train_indices]
        y_train = y_train_valid[train_indices]
        X_valid = X_train_valid[valid_indices]
        y_valid = y_train_valid[valid_indices]

        # keep track of the number of elements in each split
        counts.append(len(train_indices))

        clf = DecisionTreeClassifier(**config)
        clf.fit(X_train, y_train)

        acc = accuracy_score(y_valid, clf.predict(X_valid))
        clf_accuracies.append(acc)

    accuracies.append(np.average(clf_accuracies, weights=counts))

'''
Notice how we are computing the final accuracy not as the mean of the accuracies on each fold,
but rather as a weighted average (using np.average with the weights parameter),
where the weight is the number of elements in each partition. This is the correct way of computing
the average accuracy when each fold might have a different number of elements. Intuitively,
this is because we want larger folds to have a larger contribution to the final results.
More practically, one can prove that computing the weighted average is the same as counting the
overall number of correct predictions and dividing by the total number of elements
(since each point is only used once for the validation, we can talk about the "overall accuracy"
on X_train_valid).

So now we can get the best performing configuration (through argmax()), train a classifier on
all X_train_valid (since the cross-validation has already occurred, we can now use all the data
available for the new training). Finally, we can get our performance estimate on new data to
actually know how good our classifier is.
'''

'\nNotice how we are computing the final accuracy not as the mean of the accuracies on each fold, \nbut rather as a weighted average (using np.average with the weights parameter), \nwhere the weight is the number of elements in each partition. This is the correct way of computing \nthe average accuracy when each fold might have a different number of elements. Intuitively, \nthis is because we want larger folds to have a larger contribution to the final results. \nMore practically, one can prove that computing the weighted average is the same as counting the \noverall number of correct predictions and dividing by the total number of elements \n(since each point is only used once for the validation, we can talk about the "overall accuracy" \non X_train_valid).\n\nSo now we can get the best performing configuration (through argmax()), train a classifier on \nall X_train_valid (since the cross-validation has already occurred, we can now use all the data \navailable for the new training). F

In [43]:
best_config = list(ParameterGrid(params))[np.argmax(accuracies)]

clf = DecisionTreeClassifier(**best_config)
clf.fit(X_train_valid, y_train_valid)

accuracy_score(y_test, clf.predict(X_test))

0.9111111111111111

In [44]:

clf.tree_.feature
# clf.tree_.feature: a list of the features used at each node.
# A value of -2 indicates a leaf node (where no split occurs)

array([ 9, -2,  6, -2, 12, -2, -2], dtype=int64)

In [45]:
clf.tree_.impurity

# a list of impurity decreases for each node.
# These are computed with the following formula
# (the following is taken from scikit-learn's documentation
# for DecisionTreeClassifier:
# N_t / N * (imp - N_t_R / N_t * right_imp - N_t_L / N_t * left_imp)
# (where N is the total number of samples, N_t is the number
# of samples at the current node, N_t_L is the number of samples in
# the left child, and N_t_R is the number of samples in the right child)

array([0.65848833, 0.07986111, 0.56968858, 0.        , 0.24489796,
       0.21875   , 0.        ])

In [46]:
'''
The lists of feature, impurity and value are the pre-order visits of the tree.
Now, to compute the impurity decrease we need to know, for each node, who its children are.
This information is not readily available from the pre-order visit
'''

class Node:
    def __init__(self, impurity=0, feature=-2, value=0):
        self.right = None
        self.left = None
        self.impurity = impurity
        self.feature = feature
        self.value = value

    def __repr__(self):
        return "leaf" if self.feature == -2 else feature_names[self.feature]

'''
By default, a new Node object will be a leaf (no children, impurity=0 and no feature).
We can modify the object's attribute by directly accessing them.

Notice that we also define the __repr__ method.
This method defines a representation of our object (used, for example, when printing it).
In our case, we will use the "leaf" string for leaves, and the feature name of
the feature used for the split for split nodes.
'''

# as already mentioned, we only need
# the overall count of elements in each node,
# not the information for each class.
# The following line computes that list
values = clf.tree_.value.sum(axis=2).flatten()

nodes = [ Node(impurity, feature, value) \
         for impurity, feature, value in \
         zip(clf.tree_.impurity, clf.tree_.feature, values) ]
nodes

[color_intensity, leaf, flavanoids, leaf, proline, leaf, leaf]

In [47]:
def traverse_tree(nodes, i):
    # we use `feature==-2` to stop
    # the traversal, as we just reached a leaf
    if nodes[i].feature == -2:
        # return the offset to sum to
        # the caller's "i" to get
        # the next element (1 = "skip this element")
        return 1
    # next node is the one
    # right next to the current one
    nodes[i].right = nodes[i+1]
    offset_right = traverse_tree(nodes, i+1)
    nodes[i].left = nodes[i+offset_right+1]
    offset_left = traverse_tree(nodes, i+offset_right+1)
    return offset_right + offset_left + 1

traverse_tree(nodes, 0)

7

In [48]:
def pre_order(node, visited):
    visited.append(node)
    if node.feature==-2:
        return
    pre_order(node.right, visited)
    pre_order(node.left, visited)

po_visit = []
pre_order(nodes[0], po_visit)
print(po_visit == nodes)

True


In [49]:
def pre_order_id(node, tot_size, visited):
    left, right = node.left, node.right
    if node.feature==-2:
        visited.append(0)
        return
    decr = (node.impurity * node.value \
            - left.impurity * left.value \
            - right.impurity * right.value)/tot_size
    visited.append(decr)
    pre_order_id(node.right, tot_size, visited)
    pre_order_id(node.left, tot_size, visited)

impurity_decreases = []
pre_order_id(nodes[0], nodes[0].value, impurity_decreases)
impurity_decreases

[0.26557958363400763, 0, 0.2738611233967271, 0, 0.07706766917293234, 0, 0]

In [50]:
feature_importances = np.zeros(X.shape[1])
for feature, decr in zip(clf.tree_.feature, impurity_decreases):
    feature_importances[feature] += decr
feature_importances /= feature_importances.sum()
dict(zip(feature_names, feature_importances))

{'alcohol': 0.0,
 'malic_acid': 0.0,
 'ash': 0.0,
 'alcalinity_of_ash': 0.0,
 'magnesium': 0.0,
 'total_phenols': 0.0,
 'flavanoids': 0.44421314286613267,
 'nonflavanoid_phenols': 0.0,
 'proanthocyanins': 0.0,
 'color_intensity': 0.4307801708541132,
 'hue': 0.0,
 'od280/od315_of_diluted_wines': 0.0,
 'proline': 0.12500668627975395}