In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.io import wavfile

from sklearn.model_selection import KFold
from sklearn.model_selection import ParameterGrid

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,\
                            confusion_matrix, \
                            precision_score, \
                            recall_score, \
                            f1_score, \
                            classification_report

# from sklearn import tree
# from sklearn.tree import DecisionTreeClassifier

In [3]:
dev_path = './dev'
eval_path = './eval'

In [4]:
def load_data(data_path, phase):
    files = os.listdir(data_path)
    wav_files = [fl for fl in files if fl.endswith('.wav')]

    x = [None] * len(wav_files)
    y = [None] * len(wav_files)
    rate = [None] * len(wav_files)

    for file in wav_files:
        file_name = file.split('.')[0]
        if phase == 'dev':
            f_id, label = tuple(file_name.split('_'))
        elif phase == 'eval':
            f_id, label = file_name, float('NaN')
        else:
            raise Exception(f'Error - phase {phase} not recognised!')

        f_id, label = int(f_id), float(label)

        # wavfile.read(...) => return:
        # sr - Sample Rate
        # data - audio as array of float values

        sr, data = wavfile.read(os.path.join(data_path,file))

        x[f_id] = data.astype(np.float32)
        rate[f_id] = sr
        y[f_id] = label

    return x, y, rate

In [5]:
dev_x, dev_y, dev_sr = load_data(data_path=dev_path, phase='dev')
dev_x[:5], dev_y[:5]

([array([ 14.,  21.,   0., ...,   3., -48., -80.], dtype=float32),
  array([-2., 12.,  1., ...,  3., -3.,  3.], dtype=float32),
  array([-9., -7., -5., ..., -5., -1., -7.], dtype=float32),
  array([-256., -512.,    0., ...,    0.,    0.,    0.], dtype=float32),
  array([-20.,  10.,  26., ...,  -3.,   5., -10.], dtype=float32)],
 [4.0, 7.0, 5.0, 2.0, 3.0])